<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="POU_PLUS" Id="{a9e91d33-6a20-4b41-8e72-7456877034a3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU_PLUS
VAR
	Result:REAL;
	Value01:REAL;
	Value02:REAL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Result:=Value01+Value02;]]></ST>
    </Implementation>
    <LineIds Name="POU_PLUS">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>