<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="master" Id="{220e2799-3fee-4b6d-a227-2b1be6f3ade4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM master
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="master">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>