<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="slave" Id="{45ef1047-11b4-4376-af2d-d1048d98e90e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM slave
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="slave">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>