<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="tuning" Id="{20c43aa5-e203-4113-bfd0-a68ab6b1422a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM tuning
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="tuning">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>